# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os
os.chdir(r'C:\Users\Rahul\Desktop')

In [2]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
len(X_train)

8000

In [23]:
8000/32

250.0

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 500)

Epoch 1/500
1600/1600 [==============================] - 1s 637us/step - loss: 0.3366 - accuracy: 0.8609
Epoch 2/500
1600/1600 [==============================] - 1s 639us/step - loss: 0.3350 - accuracy: 0.8624
Epoch 3/500
1600/1600 [==============================] - 1s 641us/step - loss: 0.3343 - accuracy: 0.8626
Epoch 4/500
1600/1600 [==============================] - 1s 637us/step - loss: 0.3340 - accuracy: 0.8637
Epoch 5/500
1600/1600 [==============================] - 1s 633us/step - loss: 0.3351 - accuracy: 0.8624
Epoch 6/500
1600/1600 [==============================] - 1s 640us/step - loss: 0.3350 - accuracy: 0.8625
Epoch 7/500
1600/1600 [==============================] - 1s 645us/step - loss: 0.3349 - accuracy: 0.8611
Epoch 8/500
1600/1600 [==============================] - 1s 640us/step - loss: 0.3342 - accuracy: 0.8615
Epoch 9/500
1600/1600 [==============================] - 1s 640us/step - loss: 0.3333 - accuracy: 0.8620
Epoch 10/500
1600/1600 [==============================]

1600/1600 [==============================] - 1s 657us/step - loss: 0.3308 - accuracy: 0.8640
Epoch 79/500
1600/1600 [==============================] - 1s 643us/step - loss: 0.3311 - accuracy: 0.8644
Epoch 80/500
1600/1600 [==============================] - 1s 627us/step - loss: 0.3307 - accuracy: 0.8660
Epoch 81/500
1600/1600 [==============================] - 1s 627us/step - loss: 0.3311 - accuracy: 0.8643
Epoch 82/500
1600/1600 [==============================] - 1s 645us/step - loss: 0.3312 - accuracy: 0.8659
Epoch 83/500
1600/1600 [==============================] - 1s 645us/step - loss: 0.3306 - accuracy: 0.8659
Epoch 84/500
1600/1600 [==============================] - 1s 644us/step - loss: 0.3314 - accuracy: 0.8651
Epoch 85/500
1600/1600 [==============================] - 1s 629us/step - loss: 0.3306 - accuracy: 0.8654
Epoch 86/500
1600/1600 [==============================] - 1s 631us/step - loss: 0.3307 - accuracy: 0.8649
Epoch 87/500
1600/1600 [==============================] - 1

1600/1600 [==============================] - 1s 638us/step - loss: 0.3284 - accuracy: 0.8683
Epoch 155/500
1600/1600 [==============================] - 1s 641us/step - loss: 0.3296 - accuracy: 0.8670
Epoch 156/500
1600/1600 [==============================] - 1s 643us/step - loss: 0.3291 - accuracy: 0.8634
Epoch 157/500
1600/1600 [==============================] - 1s 629us/step - loss: 0.3286 - accuracy: 0.8673
Epoch 158/500
1600/1600 [==============================] - 1s 646us/step - loss: 0.3286 - accuracy: 0.8675
Epoch 159/500
1600/1600 [==============================] - 1s 643us/step - loss: 0.3294 - accuracy: 0.8662
Epoch 160/500
1600/1600 [==============================] - 1s 644us/step - loss: 0.3287 - accuracy: 0.8669
Epoch 161/500
1600/1600 [==============================] - 1s 638us/step - loss: 0.3292 - accuracy: 0.8651
Epoch 162/500
1600/1600 [==============================] - 1s 644us/step - loss: 0.3294 - accuracy: 0.8646
Epoch 163/500
1600/1600 [==========================

1600/1600 [==============================] - 1s 649us/step - loss: 0.3290 - accuracy: 0.8651
Epoch 231/500
1600/1600 [==============================] - 1s 649us/step - loss: 0.3280 - accuracy: 0.8662
Epoch 232/500
1600/1600 [==============================] - 1s 646us/step - loss: 0.3287 - accuracy: 0.8673
Epoch 233/500
1600/1600 [==============================] - 1s 653us/step - loss: 0.3285 - accuracy: 0.8676
Epoch 234/500
1600/1600 [==============================] - 1s 674us/step - loss: 0.3282 - accuracy: 0.8686
Epoch 235/500
1600/1600 [==============================] - 1s 664us/step - loss: 0.3274 - accuracy: 0.8659
Epoch 236/500
1600/1600 [==============================] - 1s 666us/step - loss: 0.3278 - accuracy: 0.8659
Epoch 237/500
1600/1600 [==============================] - 1s 672us/step - loss: 0.3280 - accuracy: 0.8669
Epoch 238/500
1600/1600 [==============================] - 1s 675us/step - loss: 0.3288 - accuracy: 0.8648
Epoch 239/500
1600/1600 [==========================

1600/1600 [==============================] - 1s 741us/step - loss: 0.3289 - accuracy: 0.8649
Epoch 307/500
1600/1600 [==============================] - 1s 794us/step - loss: 0.3272 - accuracy: 0.8683
Epoch 308/500
1600/1600 [==============================] - 1s 764us/step - loss: 0.3284 - accuracy: 0.8662
Epoch 309/500
1600/1600 [==============================] - 1s 751us/step - loss: 0.3272 - accuracy: 0.8690
Epoch 310/500
1600/1600 [==============================] - 1s 895us/step - loss: 0.3276 - accuracy: 0.8662
Epoch 311/500
1600/1600 [==============================] - 1s 735us/step - loss: 0.3290 - accuracy: 0.8660
Epoch 312/500
1600/1600 [==============================] - 1s 720us/step - loss: 0.3286 - accuracy: 0.8664
Epoch 313/500
1600/1600 [==============================] - 1s 744us/step - loss: 0.3283 - accuracy: 0.8661
Epoch 314/500
1600/1600 [==============================] - 1s 757us/step - loss: 0.3282 - accuracy: 0.8659
Epoch 315/500
1600/1600 [==========================

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [25]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 200  205]]


0.858

In [30]:
(1511+205)/2000

0.858

In [29]:
len(X_test)

2000